# He3BeamSim configuration file
#
BeamD   =   20.0    # beam diameter          (mm)
FoilD   =   30.0    # Si3N4 foil diameter    (mm)
FoilT   =    1.0    # Si3N4 foil thickness   (um)
PipeD   =   60.0    # He4 gas pipe diameter  (mm)
Dist    =  500.0    # foil-to-scorer distance (mm)
ScorerD =  200.0    # scorer diameter        (mm)
GasPres = 5000    # He4 gas pressure       (Torr)
