# He3BeamSim configuration file
#
BeamD   =   8.0    	# beam diameter          (mm)
FoilD   =   10.0    # Si3N4 foil diameter    (mm)
FoilT   =   1.0    	# Si3N4 foil thickness   (um)
PipeD   =   100.0   # He4 gas pipe diameter  (mm)
Dist    =  	500.0   # foil-to-scorer distance (mm)
ScorerD =  	6.0    	# scorer diameter        (mm)
GasPres = 	5    	# He4 gas pressure       (Torr)
